use crate::{
    config::theme::ThemeId, core::session::DiffMode, ui::layers::notification::Notification,
};

#[derive(Debug, Clone, PartialEq)]
pub enum Command {
    Quit,
    OpenCommandPalette,
    CloseOverlay,
    ToggleMinimap,
    SetTheme(ThemeId),
    ShowNotification(Notification),
    LoadFile { input: String },
    CheckForUpdate,
    CheckForUpdateAndNotify,
    ScrollDown { amount: usize },
    ScrollUp { amount: usize },
    ScrollLeft { amount: usize },
    ScrollRight { amount: usize },
    ScrollNamesLeft { amount: usize },
    ScrollNamesRight { amount: usize },
    JumpToColumn(usize),
    JumpToIndex(usize),
    JumpToSequence(usize),
    JumpToFeature(usize),
    JumpToEnd,
    SetRowFilter(Option<String>),
    SetGapFilter(Option<f64>),
    SetConstantFilter(Option<f64>),
    ClearAllFilters,
    PinSequence(usize),
    UnpinSequence(usize),
    SetReference(Option<usize>),
    SetConsensusMethod(libmsa::ConsensusMethod),
    SetActiveType(libmsa::AlignmentType),
    SetTranslationFrame(libmsa::ReadingFrame),
    SetDiffMode(DiffMode),
    ToggleTranslationOverlay,
    ToggleProteinView,
    LoadGff { path: String },
}
